CREATE TABLE IF NOT EXISTS mediciones (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nodo VARCHAR(50) NOT NULL,
    tipo_sensor VARCHAR(50) NOT NULL,
    valor FLOAT NOT NULL,
    unidad VARCHAR(20),
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
